function(zen_find_system_raylib out_var)
    if(TARGET raylib)
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    find_package(raylib CONFIG QUIET)
    if(TARGET raylib)
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()
    if(TARGET raylib::raylib)
        add_library(raylib INTERFACE IMPORTED)
        target_link_libraries(raylib INTERFACE raylib::raylib)
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(RAYLIB QUIET IMPORTED_TARGET raylib)
        if(TARGET PkgConfig::RAYLIB)
            add_library(raylib INTERFACE IMPORTED)
            target_link_libraries(raylib INTERFACE PkgConfig::RAYLIB)
            set(${out_var} TRUE PARENT_SCOPE)
            return()
        endif()
    endif()

    find_path(RAYLIB_INCLUDE_DIR raylib.h)
    find_library(RAYLIB_LIBRARY raylib)
    if(RAYLIB_INCLUDE_DIR AND RAYLIB_LIBRARY)
        add_library(raylib UNKNOWN IMPORTED)
        set(_raylib_deps)
        find_package(Threads QUIET)
        if(Threads_FOUND)
            list(APPEND _raylib_deps Threads::Threads)
        endif()
        find_package(OpenGL QUIET)
        if(TARGET OpenGL::GL)
            list(APPEND _raylib_deps OpenGL::GL)
        elseif(OPENGL_gl_LIBRARY)
            list(APPEND _raylib_deps "${OPENGL_gl_LIBRARY}")
        endif()
        find_library(GLFW_LIBRARY glfw)
        if(GLFW_LIBRARY)
            list(APPEND _raylib_deps "${GLFW_LIBRARY}")
        endif()
        if(UNIX AND NOT APPLE)
            list(APPEND _raylib_deps m ${CMAKE_DL_LIBS})
        endif()
        set_target_properties(raylib PROPERTIES
            IMPORTED_LOCATION "${RAYLIB_LIBRARY}"
            INTERFACE_INCLUDE_DIRECTORIES "${RAYLIB_INCLUDE_DIR}"
            INTERFACE_LINK_LIBRARIES "${_raylib_deps}")
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    set(${out_var} FALSE PARENT_SCOPE)
endfunction()
